package utp.integrador.View;

import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import utp.integrador.Model.Usuario;

public class JFPrincipal extends javax.swing.JFrame {

    static CardLayout cardLayout;
    private Usuario usuario;
    JPanel panelVacio = new JPanel();
    private JPReserva JPReserva;
    private JPCliente JPCliente;
    private JPEmpleado JPEmpleado;

    public JFPrincipal(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        mostrarDatosUsuario();
        bottonEmpleado.setVisible(false);
        if (usuario.getRol().equals("admin")) {
            bottonEmpleado.setVisible(true);
        }

        cardLayout = (CardLayout) panelDinamico.getLayout();

        JPReserva = new JPReserva();
        JPCliente = new JPCliente();
        JPEmpleado = new JPEmpleado();

        panelDinamico.add(panelVacio, "vacio");
        panelDinamico.add(JPReserva, "JPReserva");
        panelDinamico.add(JPCliente, "JPCliente");
        panelDinamico.add(JPEmpleado, "JPEmpleado");
        cardLayout.show(panelDinamico, "vacio");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEstatico = new javax.swing.JPanel();
        bottonReservar = new javax.swing.JButton();
        bottonClientes = new javax.swing.JButton();
        bottonReporte = new javax.swing.JButton();
        bottonEmpleado = new javax.swing.JButton();
        lblNombresApellidos = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        bottonSalir = new javax.swing.JButton();
        panelDinamico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelEstatico.setBackground(new java.awt.Color(255, 204, 204));

        bottonReservar.setText("RESERVAR");
        bottonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonReservarActionPerformed(evt);
            }
        });

        bottonClientes.setText("CLIENTES");
        bottonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonClientesActionPerformed(evt);
            }
        });

        bottonReporte.setText("REPORTE");

        bottonEmpleado.setText("EMPLEADOS");
        bottonEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonEmpleadoActionPerformed(evt);
            }
        });

        lblNombresApellidos.setText("...");

        lblRol.setText("...");

        bottonSalir.setText("SALIR");
        bottonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEstaticoLayout = new javax.swing.GroupLayout(panelEstatico);
        panelEstatico.setLayout(panelEstaticoLayout);
        panelEstaticoLayout.setHorizontalGroup(
            panelEstaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstaticoLayout.createSequentialGroup()
                .addGroup(panelEstaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEstaticoLayout.createSequentialGroup()
                        .addGroup(panelEstaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEstaticoLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(panelEstaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bottonEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bottonReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bottonClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bottonReservar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(panelEstaticoLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(panelEstaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRol)
                                    .addComponent(lblNombresApellidos))))
                        .addGap(0, 79, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEstaticoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bottonSalir)))
                .addContainerGap())
        );
        panelEstaticoLayout.setVerticalGroup(
            panelEstaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstaticoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(bottonSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombresApellidos)
                .addGap(28, 28, 28)
                .addComponent(lblRol)
                .addGap(185, 185, 185)
                .addComponent(bottonReservar)
                .addGap(45, 45, 45)
                .addComponent(bottonClientes)
                .addGap(42, 42, 42)
                .addComponent(bottonReporte)
                .addGap(40, 40, 40)
                .addComponent(bottonEmpleado)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        panelDinamico.setBackground(new java.awt.Color(204, 255, 255));
        panelDinamico.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEstatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEstatico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonReservarActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelDinamico, "JPReserva");
    }//GEN-LAST:event_bottonReservarActionPerformed

    private void bottonEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonEmpleadoActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelDinamico, "JPEmpleado");
    }//GEN-LAST:event_bottonEmpleadoActionPerformed

    private void bottonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonClientesActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelDinamico, "JPCliente");
    }//GEN-LAST:event_bottonClientesActionPerformed

    private void bottonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonSalirActionPerformed
        // TODO add your handling code here:
        new JFLogin().setVisible(true); // Abre la ventana principal
        dispose();
    }//GEN-LAST:event_bottonSalirActionPerformed

    private void mostrarDatosUsuario() {
        lblNombresApellidos.setText("Bienvenido, " + usuario.getNombres() + " " + usuario.getApellidos());
        lblRol.setText("Rol: " + usuario.getRol());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonClientes;
    private javax.swing.JButton bottonEmpleado;
    private javax.swing.JButton bottonReporte;
    private javax.swing.JButton bottonReservar;
    private javax.swing.JButton bottonSalir;
    private javax.swing.JLabel lblNombresApellidos;
    private javax.swing.JLabel lblRol;
    private javax.swing.JPanel panelDinamico;
    private javax.swing.JPanel panelEstatico;
    // End of variables declaration//GEN-END:variables
}
